### ISSUE TITLE
NOTIFICATION_APPRISE_URL maximum field length is too short for MS Teams configuration

### ISSUE THREAD

**Issue by hvraven** [invenhost/inventree-apprise#1]
I tried to configure the plugin to use MS Teams as described on the apprise page. However the configuration link generated is too long as it contains 3 (or 4) long tokens, exceeding the maximum length one can enter for the `NOTIFICATION_APPRISE_URL`.

I am not sure if this can be fixed here, or has to be adjusted in inventree, but I thought I start reporting it here.

**Comment by matmair** [comment]
That would need to be changed upstream and will require a new release so might take a while.

**Comment by hvraven** [comment]
Ok, thanks for the info. I created an issue in the upstream repo.
